spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/projectbankapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:projectbankapp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:projectbankapp}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.profiles.active=${SPRING_PROFILES_ACTIVE:prod}
app.security.jwt.secret=${APP_SECURITY_JWT_SECRET:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef}
app.security.jwt.access-token-expiration-seconds=${APP_SECURITY_JWT_ACCESS_TOKEN_EXPIRATION_SECONDS:900}
app.security.jwt.refresh-token-expiration-seconds=${APP_SECURITY_JWT_REFRESH_TOKEN_EXPIRATION_SECONDS:604800}
