spring.application.name=api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/projectbankapp}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:projectbankapp}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:projectbankapp}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
