services:
  backend:
    build:
      context: ./backend/api
    container_name: projectbankapp-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8080:8080"
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
    container_name: projectbankapp-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
